"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { api } from "@/lib/api";
import type { DataSource } from "@/lib/types";
import { labApi, type Catalog, type Experiment, type Json, type LabConfig, type Validation } from "@/lib/lab-api";
import { moveNode, parseConfig, patchNode, reindexBindings, secretProblem, template, templateNames, type Template } from "@/lib/lab-config";
import { ErrorBanner, LoadingState, PageHeader } from "@/components/ui";
import { Dag, JsonView, LabNav } from "./LabCommon";

export function LabEditor({id}:{id?:string}) {
 const router=useRouter();const [doc,setDoc]=useState<Experiment>({id:"",name:"新实验",description:"",config:template("basic"),bindings:{},secretNames:[],updatedAt:""});
 const [sources,setSources]=useState<DataSource[]>([]),[catalog,setCatalog]=useState<Catalog>(),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const [mode,setMode]=useState<"form"|"code">("form"),[raw,setRaw]=useState(""),[syntax,setSyntax]=useState("");const [validation,setValidation]=useState<Validation>(),[templateKey,setTemplateKey]=useState<Template>("basic");
 const [sourceId,setSourceId]=useState(""),[targetId,setTargetId]=useState(""),[secretName,setSecretName]=useState(""),[secretValue,setSecretValue]=useState(""),[secrets,setSecrets]=useState<Record<string,string>>({});
 const [nodeErrors,setNodeErrors]=useState<Record<string,boolean>>({});
 useEffect(()=>{let current=true;setLoading(true);Promise.all([api.dataSources(),labApi.catalog(),id?labApi.experiment(id):Promise.resolve(null)]).then(([s,c,d])=>{if(!current)return;setSources(s);setCatalog(c);if(d){setDoc(d);setRaw(JSON.stringify(d.config,null,2));}setSourceId(s.find(x=>x.database==="golem_lab_source")?.id??"");setTargetId(s.find(x=>x.database==="golem_lab_target")?.id??"");}).catch(e=>current&&setError(e.message)).finally(()=>current&&setLoading(false));return()=>{current=false;};},[id]);
 const changeConfig=(config:LabConfig,bindings=doc.bindings)=>{setDoc({...doc,config,bindings});setRaw(JSON.stringify(config,null,2));setValidation(undefined);};
 const updateRaw=(text:string)=>{setRaw(text);setValidation(undefined);try{const config=parseConfig(text);setDoc({...doc,config});setSyntax("");}catch(e){setSyntax(e instanceof Error?e.message:"JSON 不合法");}};
 const binding=(key:string,value:string)=>{const bindings={...doc.bindings};if(value)bindings[key]=value;else delete bindings[key];changeConfig(reindexBindings(doc.config,bindings),bindings);};
 const applyTemplate=()=>{const config=template(templateKey,sources.find(s=>s.id===sourceId)?.database,sources.find(s=>s.id===targetId)?.database);const bindings:Record<string,string>={};config.source.forEach((_,i)=>{if(sourceId)bindings[`source/${i}`]=sourceId;});config.sink.forEach((_,i)=>{if(targetId)bindings[`sink/${i}`]=targetId;});changeConfig(reindexBindings(config,bindings),bindings);setSyntax("");setNodeErrors({});};
 const validLocal=!syntax&&!Object.values(nodeErrors).some(Boolean)&&!secretProblem(doc.config);
 const save=async(preview=false)=>{setBusy(true);setError("");try{if(!validLocal)throw new Error("请修复 JSON 语法/节点配置错误，并将敏感参数改为秘密引用");const saved=await labApi.save({...doc,secrets},id??(doc.id||undefined));setDoc(saved);setRaw(JSON.stringify(saved.config,null,2));setSecrets({});setSecretValue("");if(preview){const v=await labApi.validate(saved.id);setValidation(v);}else if(!id)router.replace(`/lab/${saved.id}`);}catch(e){setError(e instanceof Error?e.message:"保存失败");}finally{setBusy(false);}};
 const run=async()=>{if(!validation?.valid||!doc.id)return;setBusy(true);setError("");try{const r=await labApi.start(doc.id);router.push(`/lab/runs/${r.id}`);}catch(e){setError(e instanceof Error?e.message:"提交失败");}finally{setBusy(false);}};
 const exportConfig=()=>{if(!validLocal)return;const blob=new Blob([JSON.stringify({name:doc.name,description:doc.description,config:doc.config,bindings:doc.bindings},null,2)],{type:"application/json"});const url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="seatunnel-experiment.json";a.click();URL.revokeObjectURL(url);};
 const importConfig=async(file:File)=>{try{const content=JSON.parse(await file.text());const config=parseConfig(JSON.stringify(content.config??content));if(secretProblem(config))throw new Error("导入含敏感字面值，请先替换为秘密引用");const bindings=content.bindings??{};setDoc({...doc,name:content.name??doc.name,description:content.description??doc.description,config,bindings});setRaw(JSON.stringify(config,null,2));setValidation(undefined);setSyntax("");setNodeErrors({});}catch(e){setError(e instanceof Error?e.message:"导入失败");}};
 if(loading)return <LoadingState/>;
 return <><PageHeader eyebrow="ZETA 2.3.13 · EXPERIMENT" title={id?"编辑实验":"创建实验"} description="JSON 是唯一配置来源。未知参数保留；凭据由绑定和秘密引用注入。" action={<div className="actions"><button className="button" disabled={busy||!validLocal} onClick={()=>save()}>保存</button><button className="button primary" disabled={busy||!validLocal} onClick={()=>save(true)}>保存并预检</button></div>}/><LabNav/>{error&&<ErrorBanner message={error}/>}
 <fieldset disabled={busy} style={{border:0,padding:0,margin:0,minWidth:0}}><section className="panel lab-panel"><div className="lab-grid"><label className="field">实验名称<input value={doc.name} onChange={e=>{setDoc({...doc,name:e.target.value});setValidation(undefined);}}/></label><label className="field">说明<input value={doc.description} onChange={e=>setDoc({...doc,description:e.target.value})}/></label></div>
 <details><summary>从可运行模板开始（替换当前配置）</summary><div className="lab-grid"><label className="field">模板<select value={templateKey} onChange={e=>setTemplateKey(e.target.value as Template)}>{Object.entries(templateNames).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label className="field">源数据库<select value={sourceId} onChange={e=>setSourceId(e.target.value)}><option value="">请选择</option>{sources.map(s=><option key={s.id} value={s.id}>{s.name} · {s.database}</option>)}</select></label><label className="field">目标数据库<select value={targetId} onChange={e=>setTargetId(e.target.value)}><option value="">请选择</option>{sources.map(s=><option key={s.id} value={s.id}>{s.name} · {s.database}</option>)}</select></label></div><button className="button" onClick={applyTemplate}>应用模板</button><p className="lab-note">使用 scripts/prepare-lab-data.py 准备专用实验库。DROP_DATA / RECREATE_SCHEMA 会清理目标数据或重建目标表。</p></details></section>
 <section className="panel lab-panel"><div className="lab-toolbar"><div className="actions"><button className={`button ${mode==="form"?"primary":""}`} disabled={!!syntax} onClick={()=>setMode("form")}>常用表单</button><button className={`button ${mode==="code"?"primary":""}`} disabled={Object.values(nodeErrors).some(Boolean)} onClick={()=>{setRaw(JSON.stringify(doc.config,null,2));setMode("code");}}>原生 JSON</button></div><div className="actions"><button className="button" disabled={!validLocal} onClick={exportConfig}>导出</button><label className="button">导入<input type="file" hidden accept=".json,application/json" onChange={e=>{const f=e.target.files?.[0];if(f)void importConfig(f);e.target.value="";}}/></label></div></div>
 {mode==="code"?<><p className="lab-note">托管字段使用 ${"{datasource:source/0:password}"} 引用。额外秘密使用 ${"{secret:name}"}。其他未知字段和嵌套值不会被重新生成。</p><textarea aria-label="原生 JSON 配置" className="lab-code-editor" spellCheck={false} value={raw} onChange={e=>updateRaw(e.target.value)}/>{syntax&&<ErrorBanner message={syntax}/>}<button className="button" disabled={!!syntax} onClick={()=>setRaw(JSON.stringify(doc.config,null,2))}>格式化</button></>:<>
 <div className="lab-grid">{["parallelism","checkpoint.interval","checkpoint.timeout","read_limit.rows_per_second"].map(key=><label className="field" key={key}>{key}<input type="number" min="1" value={typeof doc.config.env[key]==="number"?doc.config.env[key]:""} placeholder="未显式设置" onChange={e=>{const env={...doc.config.env};if(e.target.value)env[key]=Number(e.target.value);else delete env[key];changeConfig({...doc.config,env});}}/></label>)}</div><p className="lab-note">这里只展示用户显式设置值。默认值见参数目录；引擎未返回的参数不会标为“已生效”。</p>
 {(["source","transform","sink"] as const).map(section=><div key={section} className="lab-nodes"><div className="lab-toolbar"><h3>{section.toUpperCase()}</h3><button className="button" onClick={()=>changeConfig({...doc.config,[section]:[...doc.config[section],{plugin_name:section==="transform"?"Sql":"Jdbc",...(section==="sink"?{plugin_input:[]}: {plugin_output:`${section}_${doc.config[section].length}`})}]})}>添加节点</button></div>{doc.config[section].map((node,i)=>{const key=`${section}/${i}`;return <div className="lab-node" key={key}><div className="lab-toolbar"><strong>{key} · {node.plugin_name}</strong><div className="actions"><button className="button small" disabled={i===0} onClick={()=>{const n=moveNode(doc.config,doc.bindings,section,i,i-1);changeConfig(n.config,n.bindings);setNodeErrors({});}}>上移</button><button className="button small" disabled={i===doc.config[section].length-1} onClick={()=>{const n=moveNode(doc.config,doc.bindings,section,i,i+1);changeConfig(n.config,n.bindings);setNodeErrors({});}}>下移</button><button className="button small" onClick={()=>{const n=moveNode(doc.config,doc.bindings,section,i,null);changeConfig(n.config,n.bindings);setNodeErrors({});}}>删除</button></div></div><div className="lab-grid">{section!=="transform"?<label className="field">绑定数据源<select value={doc.bindings[key]??""} onChange={e=>binding(key,e.target.value)}><option value="">请选择</option>{sources.map(s=><option key={s.id} value={s.id}>{s.name} · {s.database}</option>)}</select></label>:<label className="field">Transform<select value={node.plugin_name} onChange={e=>changeConfig(patchNode(doc.config,section,i,{plugin_name:e.target.value}))}>{catalog?.groups.filter(g=>g.id.startsWith("transform.")&&g.id.split(".").length===2&&g.plugin).map(g=><option key={g.id} value={g.plugin}>{g.plugin}{g.installed?"":"（未安装）"}</option>)}</select></label>}{section!=="sink"&&<label className="field">plugin_output<input value={String(node.plugin_output??"")} onChange={e=>changeConfig(patchNode(doc.config,section,i,{plugin_output:e.target.value}))}/></label>}{section!=="source"&&<label className="field">plugin_input（逗号分隔）<input value={Array.isArray(node.plugin_input)?node.plugin_input.join(", "):String(node.plugin_input??"")} onChange={e=>changeConfig(patchNode(doc.config,section,i,{plugin_input:e.target.value.split(",").map(x=>x.trim()).filter(Boolean)}))}/></label>}</div>
 {section!=="transform"&&[section==="source"?"table_path":"table",section==="source"?"fetch_size":"batch_size"].map(field=><label className="field" key={field}>{field}<input value={typeof node[field]==="string"||typeof node[field]==="number"?String(node[field]):""} placeholder="未显式设置" onChange={e=>{const config=structuredClone(doc.config);if(e.target.value)config[section][i][field]=field.endsWith("size")?Number(e.target.value):e.target.value;else delete config[section][i][field];changeConfig(config);}}/></label>)}
 <NodeJson value={node} label={`${key} 完整参数`} onChange={value=>{const config={...doc.config,[section]:doc.config[section].map((n,j)=>i===j?value:n)};changeConfig(config as LabConfig);}} onError={bad=>setNodeErrors(prev=>prev[key]===bad?prev:{...prev,[key]:bad})}/><Link className="lab-link" href={`/lab/catalog?group=${encodeURIComponent(`${section}.${node.plugin_name}`)}`}>查看此插件完整参数、默认值与依赖条件 →</Link></div>;})}</div>)}
 <details><summary>完整 env 参数（保留未知项）</summary><NodeJson value={doc.config.env} label="env 参数" onChange={env=>changeConfig({...doc.config,env})} onError={bad=>setNodeErrors(p=>p.env===bad?p:{...p,env:bad})}/></details></>}
 {mode==="code"&&<div className="lab-grid">{(["source","sink"] as const).flatMap(section=>doc.config[section].map((_,i)=><label className="field" key={`${section}/${i}`}>{section}/{i} 数据源绑定<select value={doc.bindings[`${section}/${i}`]??""} onChange={e=>binding(`${section}/${i}`,e.target.value)}><option value="">请选择</option>{sources.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>))}</div>}
 {!secretProblem(doc.config)?null:<ErrorBanner message="发现敏感字面值；请改为秘密引用后保存或导出。"/>}</section>
 <section className="panel lab-panel"><details><summary>加密秘密引用 · 已配置 {doc.secretNames.length} 项</summary><p className="lab-note">值只写入加密存储，不进入配置导出。已配置名称：{doc.secretNames.join(", ")||"无"}</p><div className="lab-grid"><label className="field">引用名称<input value={secretName} onChange={e=>setSecretName(e.target.value)}/></label><label className="field">秘密值<input type="password" autoComplete="new-password" value={secretValue} onChange={e=>setSecretValue(e.target.value)}/></label></div><button className="button" disabled={!/^[\w-]{1,120}$/.test(secretName)||!secretValue} onClick={()=>{setSecrets({...secrets,[secretName]:secretValue});setSecretValue("");setValidation(undefined);}}>加入待保存秘密</button><p className="lab-note">待保存：{Object.keys(secrets).join(", ")||"无"}</p></details></section>
 <section className="panel lab-panel"><h3>配置拓扑</h3><Dag config={doc.config}/></section>
 {validation&&<section className="panel lab-panel"><h3>提交预览 · {validation.valid?"预检通过":"需要修正"}</h3><p className="lab-note">{validation.validationLevel}</p>{validation.errors.map((e,i)=><ErrorBanner key={i} message={e}/>)}<details><summary>校验提示（{validation.warnings.length}）</summary><ul>{validation.warnings.map((w,i)=><li key={i}>{w}</li>)}</ul></details><details open><summary>将发送给引擎的配置（已脱敏，包含目标表和写入策略）</summary><JsonView value={validation.preview}/></details><details><summary>源表字段预检</summary><JsonView value={validation.sourceSchemas}/></details><button className="button primary" disabled={!validation.valid||busy} onClick={run}>提交真实 Zeta 运行</button></section>}
 </fieldset></>;
}
function NodeJson({value,label,onChange,onError}:{value:Record<string,Json>;label:string;onChange:(value:Record<string,Json>)=>void;onError:(bad:boolean)=>void}) {
 const [text,setText]=useState(JSON.stringify(value,null,2)),[error,setError]=useState("");const serialized=JSON.stringify(value);
 useEffect(()=>{setText(JSON.stringify(JSON.parse(serialized),null,2));setError("");},[serialized]);
 return <details><summary>{label}</summary><textarea aria-label={label} className="lab-code-editor compact" value={text} spellCheck={false} onChange={e=>{setText(e.target.value);try{const parsed=JSON.parse(e.target.value);if(!parsed||typeof parsed!=="object"||Array.isArray(parsed))throw new Error();setError("");onError(false);onChange(parsed);}catch{setError("JSON 对象语法不正确");onError(true);}}}/>{error&&<p role="alert">{error}</p>}</details>;
}
