"use client";
import { useEffect,useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { labApi,type MetricSample,type Run } from "@/lib/lab-api";
import { ACTIVE } from "@/lib/lab-config";
import { PageHeader,LoadingState,ErrorBanner,duration } from "@/components/ui";
import { LabNav,LabStatus,JsonView,Dag,Chart,numberValue,resourceValue,metric,TableMetrics } from "./LabCommon";
export function LabRun({id}:{id:string}) {
 const router=useRouter();const [run,setRun]=useState<Run>(),[samples,setSamples]=useState<MetricSample[]>([]),[logs,setLogs]=useState<{lines:string[];source?:string;error?:string}>(),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 useEffect(()=>{let current=true;let timer:ReturnType<typeof setTimeout>;setRun(undefined);setSamples([]);setLogs(undefined);const load=async()=>{try{const [r,m,l]=await Promise.all([labApi.run(id),labApi.metrics(id),labApi.logs(id)]);if(current){setRun(r);setSamples(m);setLogs(l);}}catch(e){if(current)setError(e instanceof Error?e.message:"加载失败");}finally{if(current)timer=setTimeout(load,2000);}};void load();return()=>{current=false;clearTimeout(timer);};},[id]);
 const action=async(a:"cancel"|"savepoint"|"restore")=>{setBusy(true);setError("");try{const result=await labApi.action(id,a);if(a==="restore")router.push(`/lab/runs/${result.id}`);else setRun(result);}catch(e){setError(e instanceof Error?e.message:"操作失败");}finally{setBusy(false);}};
 if(!run)return <>{error&&<ErrorBanner message={error}/>}<LoadingState/></>;
 const times=samples.map(s=>s.time),metrics=run.observation.job?.metrics;
 return <><PageHeader eyebrow="IMMUTABLE RUN SNAPSHOT" title={run.experimentName} description={`Zeta ${run.engineVersion} · 外部 jobId ${run.externalJobId}`} action={<LabStatus status={run.status}/>}/><LabNav/>{error&&<ErrorBanner message={error}/>}<div className="lab-toolbar"><Link className="lab-link" href={`/lab/${run.experimentId}`}>返回实验配置</Link><div className="actions">{ACTIVE.has(run.status)&&<><button className="button" disabled={busy||["SAVING","CANCELING"].includes(run.status)} onClick={()=>action("cancel")}>取消运行</button><button className="button primary" disabled={busy||["SAVING","CANCELING"].includes(run.status)} onClick={()=>action("savepoint")}>保存点停止</button></>}{run.status==="SAVED"&&<button className="button primary" disabled={busy} onClick={()=>action("restore")}>从原保存点恢复</button>}</div></div>
 {run.status==="SAVED"&&<div className="alert">保存点暂停不表示全量同步成功。恢复会创建新平台运行，复用原执行快照与外部 jobId。</div>}{run.observation.lastError&&<ErrorBanner message={run.observation.lastError}/>}{run.observation.job?.errorMsg&&<ErrorBanner message={run.observation.job.errorMsg}/>}
 <div className="lab-stats">{[["已读取",metric(metrics,"SourceReceivedCount")],["已写入",metric(metrics,"SinkWriteCount")],["已提交",metric(metrics,"SinkCommittedCount")],["平台耗时",duration(run.createdAt,run.observation.finishedAt)]].map(([k,v])=><div className="panel lab-panel" key={k}><small>{k}</small><strong>{v}</strong></div>)}</div>
 <section className="panel lab-panel"><h3>作业拓扑</h3><Dag config={run.config}/><details><summary>引擎实际 DAG（未返回时不可用）</summary><JsonView value={run.observation.job?.jobDag}/></details></section>
 <section className="panel lab-panel"><Chart label="读取 / 写入吞吐（行/秒）" series={[{name:"读取",times,values:samples.map(s=>numberValue(s.metrics?.SourceReceivedQPS))},{name:"写入",times,values:samples.map(s=>numberValue(s.metrics?.SinkWriteQPS))}]}/><h3>分表与提交指标</h3><p className="lab-note">保留引擎原始指标名和表标签。缺失表示不可用，累计值和速率不可互换。</p><TableMetrics metrics={metrics}/><details><summary>全部原始指标</summary><JsonView value={metrics}/></details></section>
 <section className="panel lab-panel"><h3>Zeta 进程资源 · 多作业共享</h3><Chart label="进程 CPU (%)" series={[{name:"Zeta",times,values:samples.map(s=>resourceValue(s,"load.process"))}]}/><Chart label="堆内存使用 (MiB)" series={[{name:"Zeta",times,values:samples.map(s=>resourceValue(s,"heap.memory.used"))}]}/><Chart label="Minor GC 累计次数" series={[{name:"Zeta",times,values:samples.map(s=>resourceValue(s,"minor.gc.count"))}]}/><details><summary>最近资源采样（包含 GC 时间）</summary><JsonView value={samples.at(-1)?.resources}/></details></section>
 <section className="panel lab-panel"><h3>Checkpoint / Savepoint</h3><p className="lab-note">按引擎响应展示；仅返回 jobId 代表没有可展示的统计。普通 JDBC 不因启用 Checkpoint 而自动获得 exactly-once。</p><JsonView value={run.observation.checkpoints}/></section>
 <section className="panel lab-panel"><h3>运行事件</h3><ol className="lab-events">{run.events?.map((e,i)=><li key={i}><time>{e.time}</time><strong>{e.type}</strong><span>{e.message}</span></li>)}</ol></section>
 <section className="panel lab-panel"><h3>脱敏日志</h3><p className="lab-note">{logs?.source??logs?.error??"不可用"}</p><pre className="lab-json">{logs?.lines.join("\n")||"暂无可归属此 jobId 的日志行"}</pre></section>
 <section className="panel lab-panel"><h3>不可变配置快照</h3><p className="lab-note">SHA-256：{run.configDigest}</p>{run.restoredFrom&&<Link className="lab-link" href={`/lab/runs/${run.restoredFrom}`}>原运行：{run.restoredFrom}</Link>}<JsonView value={run.config}/><details><summary>提交前只读字段快照与校验记录</summary><JsonView value={run.validation}/></details></section></>;
}
