"use client";
import { useEffect,useRef,useState } from "react";
import { labApi,type Run } from "@/lib/lab-api";
import { flatten,schemaMap } from "@/lib/lab-config";
import { PageHeader,ErrorBanner } from "@/components/ui";
import { LabNav,RunsTable,Chart,JsonView,numberValue,resourceValue,TableMetrics } from "@/components/lab/LabCommon";
export default function Page(){const [runs,setRuns]=useState<Run[]>([]),[ids,setIds]=useState<string[]>([]),[comparison,setComparison]=useState<Run[]>([]),[error,setError]=useState(""),[busy,setBusy]=useState(false);const generation=useRef(0);
 useEffect(()=>{let active=true;labApi.runs().then(r=>active&&setRuns(r)).catch(e=>active&&setError(e.message));return()=>{active=false;generation.current++;};},[]);
 const compare=async()=>{const seq=++generation.current;setBusy(true);setError("");try{const data=await labApi.compare(ids);if(seq===generation.current)setComparison(data);}catch(e){if(seq===generation.current)setError(e instanceof Error?e.message:"对比失败");}finally{if(seq===generation.current)setBusy(false);}};
 const schemaFlat=comparison.map(r=>schemaMap(r.validation.sourceSchemas));const schemaKeys=Array.from(new Set(schemaFlat.flatMap(Object.keys))).filter(k=>new Set(schemaFlat.map(f=>f[k]??"字段不存在")).size>1).sort();
 const flat=comparison.map(r=>flatten(r.authoringConfig)),keys=Array.from(new Set(flat.flatMap(Object.keys))).filter(k=>new Set(flat.map(f=>f[k]??"未设置")).size>1).sort();
 return <><PageHeader eyebrow="MANUAL EXPERIMENT COMPARISON" title="运行对比" description="选择 2–4 次运行。保存点暂停、失败与正常完成的耗时和吞吐不能直接等价比较。" action={<button className="button primary" disabled={ids.length<2||busy} onClick={compare}>比较 {ids.length} 次运行</button>}/><LabNav/>{error&&<ErrorBanner message={error}/>}<section className="panel"><RunsTable runs={runs} selected={ids} onSelect={id=>{generation.current++;setBusy(false);setComparison([]);setIds(prev=>prev.includes(id)?prev.filter(x=>x!==id):prev.length<4?[...prev,id]:prev);}}/></section>{comparison.length>0&&<><section className="panel lab-panel"><h3>选中运行</h3><RunsTable runs={comparison}/><h3>显式配置差异</h3><div className="table-wrap"><table className="data-table"><thead><tr><th>JSON 路径</th>{comparison.map(r=><th key={r.id}>{r.experimentName} · {r.id.slice(0,8)}</th>)}</tr></thead><tbody>{keys.map(k=><tr key={k}><td><code>{k}</code></td>{flat.map((f,i)=><td key={i}><code>{f[k]??"未设置"}</code></td>)}</tr>)}</tbody></table>{!keys.length&&<p className="lab-note">显式配置相同；请同时核对绑定、字段快照和运行状态。</p>}</div><h3>源字段变化（两次批量运行之间）</h3><div className="table-wrap"><table className="data-table"><thead><tr><th>节点 / 表 / 字段</th>{comparison.map(r=><th key={r.id}>{r.id.slice(0,8)}</th>)}</tr></thead><tbody>{schemaKeys.map(k=><tr key={k}><td>{k}</td>{schemaFlat.map((f,i)=><td key={i}><code>{f[k]??"字段不存在"}</code></td>)}</tr>)}</tbody></table>{!schemaKeys.length&&<p className="lab-note">可获得的源表字段快照无差异；查询推导结构未在静态预检中展开。</p>}</div><h3>绑定与源字段快照（批量结构变化）</h3>{comparison.map(r=><details key={r.id}><summary>{r.experimentName} · {r.id.slice(0,8)}</summary><TableMetrics metrics={r.observation.job?.metrics}/><JsonView value={{bindings:r.bindings,sourceSchemas:r.validation.sourceSchemas,metrics:r.observation.job?.metrics}}/></details>)}</section><section className="panel lab-panel">{["SourceReceivedQPS","SinkWriteQPS"].map(key=><Chart key={key} label={`${key} · 行/秒`} series={comparison.map(r=>({name:`${r.experimentName} ${r.id.slice(0,8)}`,times:(r.samples??[]).map(s=>s.time),values:(r.samples??[]).map(s=>numberValue(s.metrics?.[key]))}))}/>)}</section><section className="panel lab-panel"><h3>引擎进程资源曲线 · 多作业共享</h3>{["load.process","heap.memory.used","minor.gc.count"].map(key=><Chart key={key} label={key} series={comparison.map(r=>({name:r.id.slice(0,8),times:(r.samples??[]).map(s=>s.time),values:(r.samples??[]).map(s=>resourceValue(s,key))}))}/>)}</section></>}</>;
}
