CREATE TABLE lab_experiment (
 id VARCHAR(36) PRIMARY KEY,
 document_json CLOB NOT NULL,
 archived BOOLEAN NOT NULL DEFAULT FALSE,
 updated_at TIMESTAMP NOT NULL
);
CREATE TABLE lab_binding (
 experiment_id VARCHAR(36) NOT NULL REFERENCES lab_experiment(id),
 node_key VARCHAR(120) NOT NULL,
 data_source_id VARCHAR(36) NOT NULL REFERENCES data_source_config(id),
 PRIMARY KEY(experiment_id, node_key)
);
CREATE TABLE lab_secret (
 experiment_id VARCHAR(36) NOT NULL REFERENCES lab_experiment(id),
 secret_name VARCHAR(120) NOT NULL,
 encrypted_value CLOB NOT NULL,
 PRIMARY KEY(experiment_id, secret_name)
);
CREATE TABLE lab_run (
 id VARCHAR(36) PRIMARY KEY,
 experiment_id VARCHAR(36) NOT NULL REFERENCES lab_experiment(id),
 external_job_id VARCHAR(64) NOT NULL,
 status VARCHAR(32) NOT NULL,
 execution_cipher CLOB NOT NULL,
 snapshot_json CLOB NOT NULL,
 observation_json CLOB NOT NULL,
 created_at TIMESTAMP NOT NULL
);
CREATE INDEX idx_lab_run_experiment ON lab_run(experiment_id, created_at);
CREATE INDEX idx_lab_run_status ON lab_run(status);
CREATE TABLE lab_run_binding (
 run_id VARCHAR(36) NOT NULL REFERENCES lab_run(id),
 node_key VARCHAR(120) NOT NULL,
 data_source_id VARCHAR(36) NOT NULL REFERENCES data_source_config(id),
 PRIMARY KEY(run_id, node_key)
);
CREATE TABLE lab_run_event (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 run_id VARCHAR(36) NOT NULL REFERENCES lab_run(id),
 event_json CLOB NOT NULL,
 created_at TIMESTAMP NOT NULL
);
CREATE INDEX idx_lab_event_run ON lab_run_event(run_id, id);
CREATE TABLE lab_metric_sample (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 run_id VARCHAR(36) NOT NULL REFERENCES lab_run(id),
 sample_json CLOB NOT NULL,
 created_at TIMESTAMP NOT NULL
);
CREATE INDEX idx_lab_sample_run ON lab_metric_sample(run_id, id);
