"use client";
import { useEffect,useState } from "react";
import Link from "next/link";
import { labApi,type Catalog } from "@/lib/lab-api";
import { PageHeader,LoadingState,ErrorBanner } from "@/components/ui";
import { LabNav,JsonView } from "@/components/lab/LabCommon";
export default function Page(){const [catalog,setCatalog]=useState<Catalog>(),[query,setQuery]=useState(""),[group,setGroup]=useState(""),[error,setError]=useState("");useEffect(()=>{let active=true;setGroup(new URLSearchParams(window.location.search).get("group")??"");labApi.catalog().then(c=>active&&setCatalog(c)).catch(e=>active&&setError(e.message));return()=>{active=false;};},[]);
 return <><PageHeader eyebrow="OPTIONS & FACTORY" title="版本化参数目录" description="来源于本机安装包的 Options / Factory，默认值不等于引擎已生效值。"/><LabNav/>{error&&<ErrorBanner message={error}/>}<section className="panel lab-panel"><div className="lab-grid"><label className="field">搜索原始键名、说明或类型<input value={query} onChange={e=>setQuery(e.target.value)}/></label><label className="field">作用域<select value={group} onChange={e=>setGroup(e.target.value)}><option value="">全部分组</option>{catalog?.groups.map(g=><option value={g.id} key={g.id}>{g.id}</option>)}</select></label></div></section>{!catalog?<LoadingState/>:catalog.groups.filter(g=>!group||g.id===group).map(g=>{const options=g.options.filter(o=>`${o.key} ${o.description} ${o.type}`.toLowerCase().includes(query.toLowerCase()));if(!options.length)return null;return <section key={g.id} className="panel lab-panel"><div className="lab-toolbar"><h3>{g.id}</h3><a className="lab-link" href={g.documentation} target="_blank" rel="noreferrer">2.3.13 官方说明 ↗</a></div><p className="lab-note">文档支持 · {g.installed?"本机已安装":"本机未安装 / 依赖缺失"} · {g.platformVerified?"本平台有成功运行记录（仅限记录中的配置）":"本平台尚无成功运行记录"}</p>{g.verifiedRunIds?.length>0&&<Link className="lab-link" href={`/lab/runs/${g.verifiedRunIds[0]}`}>查看验证依据 →</Link>}{g.requirements&&<div className="alert">{g.requirements}</div>}<div className="table-wrap"><table className="data-table"><thead><tr><th>原始键名 / 作用域</th><th>类型 / 必填</th><th>定义默认值</th><th>说明 / 生效条件 / 来源</th></tr></thead><tbody>{options.map(o=><tr key={o.key}><td><code>{o.key}</code><small className="lab-sub">{g.id} · 2.3.13</small></td><td>{o.type}<small className="lab-sub">{o.required?"必填（有默认值可省略）":"可选 / 条件必填"}</small></td><td><code>{o.defaultValue===null?"无默认值":JSON.stringify(o.defaultValue)}</code></td><td className="lab-option-description">{o.description}{o.condition&&<p>{o.condition}</p>}{o.enumValues&&<p>枚举：{o.enumValues.join(", ")}</p>}<details><summary>参数依据与约束</summary><a className="lab-link" href={o.sourceUrl} target="_blank" rel="noreferrer">{o.origin} ↗</a><JsonView value={{javaType:o.javaType,conditions:o.conditions,fallbackKeys:o.fallbackKeys}}/></details></td></tr>)}</tbody></table></div><details><summary>插件必填与互斥规则</summary><JsonView value={g.rules}/></details></section>;})}</>;
}
